import type { PlaceCategory } from "./types"

export const placeCategories: PlaceCategory[] = [
  {
    id: "cafes",
    name: "Cafes & Food Spots",
    emoji: "☕",
    tags: ["aesthetic", "cozy", "vegan-friendly", "famous", "hidden gem"],
    vibe: ["chill", "warm", "Instagrammable"],
    description: "Discover cozy cafes and unique food spots with amazing vibes",
  },
  {
    id: "parks",
    name: "Parks & Gardens",
    emoji: "🌿",
    tags: ["urban", "picnic", "romantic", "peaceful", "floral"],
    vibe: ["calm", "nature", "relaxing"],
    description: "Find peaceful green spaces perfect for relaxation",
  },
  {
    id: "historical",
    name: "Historical Places",
    emoji: "🏰",
    tags: ["fort", "palace", "monument", "heritage site"],
    vibe: ["majestic", "educational"],
    description: "Explore places rich in history and culture",
  },
  {
    id: "religious",
    name: "Religious Sites",
    emoji: "🛕",
    tags: ["temple", "mosque", "church", "shrine"],
    vibe: ["spiritual", "quiet"],
    description: "Find peace in sacred and spiritual places",
  },
  {
    id: "nature",
    name: "Natural Attractions",
    emoji: "🌄",
    tags: ["waterfalls", "hills", "lakes", "beaches", "nature parks"],
    vibe: ["adventurous", "refreshing"],
    description: "Connect with nature in breathtaking locations",
  },
  {
    id: "museums",
    name: "Museums & Art",
    emoji: "🖼️",
    tags: ["cultural", "modern", "historical", "interactive"],
    vibe: ["artistic", "thoughtful"],
    description: "Immerse yourself in art and culture",
  },
  {
    id: "shopping",
    name: "Shopping Markets",
    emoji: "🛍️",
    tags: ["flea markets", "bazaars", "shopping streets"],
    vibe: ["lively", "colorful"],
    description: "Discover unique shopping experiences",
  },
  {
    id: "adventure",
    name: "Adventure Activities",
    emoji: "🚴",
    tags: ["trekking", "ziplining", "boating", "biking"],
    vibe: ["thrilling", "energetic"],
    description: "Get your adrenaline pumping with exciting activities",
  },
  {
    id: "beaches",
    name: "Beaches & Coastal",
    emoji: "🏖️",
    tags: ["sunbathing", "water sports", "sea views"],
    vibe: ["relaxing", "breezy"],
    description: "Enjoy sun, sand, and sea vibes",
  },
  {
    id: "nightlife",
    name: "Nightlife & Pubs",
    emoji: "🎶",
    tags: ["bars", "live music", "lounges", "rooftop"],
    vibe: ["vibrant", "social"],
    description: "Experience the city's nighttime energy",
  },
  {
    id: "bookstores",
    name: "Bookstores & Libraries",
    emoji: "📚",
    tags: ["hidden", "vintage", "public libraries", "indie stores"],
    vibe: ["quiet", "cozy", "nostalgic"],
    description: "Find literary havens and quiet reading spots",
  },
  {
    id: "viewpoints",
    name: "Scenic Viewpoints",
    emoji: "📸",
    tags: ["sunset", "skyline", "hilltops", "sunrise point"],
    vibe: ["romantic", "aesthetic"],
    description: "Capture breathtaking views and moments",
  },
]
